// Objective-C API for talking to github.com/chrisdmacrae/com.relirc.core/macos Go package.
//   gobind -lang=objc github.com/chrisdmacrae/com.relirc.core/macos
//
// File is generated by gobind. Do not edit.

#ifndef __Macos_H__
#define __Macos_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MacosTest;

@interface MacosTest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

#endif
